[build]
  # Frontend build command with Prisma setup
  command = "npm install && npm run build:netlify"
  # Frontend build output directory 
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  # Database URL for Netlify Connect - set this in Netlify dashboard
  DATABASE_URL = "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19TUE40WUV1SXpiUlN0dFVQY3ZFU04iLCJhcGlfa2V5IjoiMDFLNzRKOFJYUDdHTjg1VFpTMzdTMzVENzIiLCJ0ZW5hbnRfaWQiOiIzNzk5ODBjYTNmMTRkY2FhNTIwM2UxZmZhYTE4YmZmMDBkYzRlYTM3NGYyODFkNjg3N2JlYTZjYjU0ZTExMDYxIiwiaW50ZXJuYWxfc2VjcmV0IjoiMTVjMmYxZDgtNjY3NS00NGNmLWFiZTctMmQ0YTkzNGE2OTVjIn0.dTJH0srWwjacJCmKgOz1l0LRAuMQOckj4LbPmYAiGSo"

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Handle API routing to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  # For local development
  command = "cd frontend && npm run dev"
  targetPort = 4321
  port = 8888
  publish = "frontend/dist"