[build]
  # Frontend build command
  command = "npm run build:frontend"
  # Frontend build output directory 
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  # Railway backend API URL
  PUBLIC_API_URL = "https://myfoodmap-production.up.railway.app/api"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  # For local development
  command = "cd frontend && npm run dev"
  targetPort = 4321
  port = 8888
  publish = "frontend/dist"